'use client';
import Image from 'next/image';
import { useRef,useState } from 'react';
import { motion,useScroll,useSpring,useTransform,useMotionTemplate,useMotionValueEvent,type MotionValue } from 'framer-motion';
import { useCinematicMotion } from './motion-provider';
import { whatsapp } from '@/lib/services';
const chapters=[
 {id:'comfort',label:'COMFORT',eyebrow:'THE PERSONAL SPACE',title:'EVERY DETAIL.',em:'YOUR SIGNATURE.',copy:<>Tailored textures. Considered comfort.<br/>A cabin that feels like it was made for you.</>,services:<>Premium seat covers · 3D & 7D floor mats<br/>Sunshades · Lumbar & neck pillows</>,cta:'Make it personal',subject:'interior upgrades',image:'interior.jpg'},
 {id:'sound',label:'SOUND & LIGHT',eyebrow:'THE SENSORY EXPERIENCE',title:'DON’T JUST',em:'HEAR IT. FEEL IT.',copy:<>Sound that surrounds you.<br/>Light that changes the atmosphere.</>,services:<>Amplifiers, DSP & audio · Android touchscreens<br/>Ambient LED lighting · Dashcams</>,cta:'Find your frequency',subject:'audio and technology',image:'interior.jpg'},
 {id:'performance',label:'PERFORMANCE',eyebrow:'THE DRIVING CHARACTER',title:'MAKE YOUR',em:'PRESENCE FELT.',copy:<>The stance. The response. The character.<br/>A drive with your name on it.</>,services:<>Alloy wheels · ECU tuning</>,cta:'Talk performance',subject:'wheels and ECU tuning',image:'wheel.jpg'}
];
function Scene({index,progress,active}:{index:number,progress:MotionValue<number>,active:number}){
 const enabled=useCinematicMotion();const chapter=chapters[index];
 const opacity=useTransform(progress,value=>{const p=value*3-index;const incoming=index===0?1:Math.max(0,Math.min(1,p/.18));const outgoing=index===2?1:1-Math.max(0,Math.min(1,(p-.8)/.2));return incoming*outgoing});
 const y=useTransform(progress,value=>{const p=value*3-index;return -Math.max(0,Math.min(1,(p-.8)/.2))*55+Math.max(0,1-p/.18)*65});
 const visibility=useTransform(opacity,v=>v>.001?'visible' as const:'hidden' as const);
 return <motion.article className="scene" id={chapter.id} aria-hidden={enabled?active!==index:undefined} inert={enabled&&active!==index} style={enabled?{opacity,y,visibility,translateY:'-50%'}:undefined}><p className="eyebrow">0{index+1} / {chapter.eyebrow}</p><h2>{chapter.title}<br/><em>{chapter.em}</em></h2><p>{chapter.copy}</p><div className="scene-services">{chapter.services}</div><a className="text-link" href={whatsapp(chapter.subject)} target="_blank" rel="noopener">{chapter.cta} ↗</a></motion.article>
}
function SceneImage({index,progress}:{index:number,progress:MotionValue<number>}){const enabled=useCinematicMotion();const clip=useTransform(progress,v=>100-Math.max(0,Math.min(1,(v*3-index)/.24))*100);const clipPath=useMotionTemplate`inset(0 ${clip}% 0 0)`;const scale=useTransform(progress,v=>(index===1?1.4:1.12)+Math.max(0,Math.min(1,v*3-index))*.12);return <motion.div className="scene-image-layer" style={enabled?{clipPath:index?clipPath:undefined,scale,opacity:1}:{opacity:index?0:1}}><Image src={'/assets/'+chapters[index].image} alt="" fill sizes="100vw" className="scene-image"/></motion.div>}
function ChapterButton({index,progress,onClick,active}:{index:number,progress:MotionValue<number>,onClick:()=>void,active:number}){const fill=useTransform(progress,v=>Math.max(0,Math.min(1,v*3-index)));return <button type="button" onClick={onClick} className={active===index?'active':''} aria-pressed={active===index}><span>0{index+1}</span>{chapters[index].label}<motion.i style={{scaleX:fill}}/></button>}
export function Journey(){const ref=useRef<HTMLElement>(null);const enabled=useCinematicMotion();const {scrollYProgress}=useScroll({target:ref,offset:['start start','end end']});const progress=useSpring(scrollYProgress,{stiffness:150,damping:35,restDelta:.001});const [active,setActive]=useState(0);useMotionValueEvent(progress,'change',v=>setActive(Math.min(2,Math.floor(Math.max(0,v)*3))));const dash=useTransform(progress,[0,1],[100,0]);const rotate=useTransform(progress,[0,1],[0,360]);const seamX=useTransform(progress,v=>{const phase=v*3%1;return `${110-Math.max(0,Math.min(1,(phase-.76)/.24))*220}vw`});const seamOpacity=useTransform(progress,v=>v<2/3?Math.sin(Math.max(0,Math.min(1,(v*3%1-.76)/.24))*Math.PI)*.22:0);
 const go=(index:number)=>{if(enabled&&ref.current){const top=ref.current.getBoundingClientRect().top+window.scrollY;window.scrollTo({top:top+(ref.current.offsetHeight-window.innerHeight)*(index+.25)/3,behavior:'smooth'})}else document.getElementById(chapters[index].id)?.scrollIntoView({behavior:'auto'})};
 return <section className="journey" id="journey" ref={ref} aria-label="Explore comfort, sound and performance"><div className="cinema-stage"><div className="cinema-images" aria-hidden="true">{chapters.map((_,i)=><SceneImage key={i} index={i} progress={progress}/>)}</div><div className="cinema-overlay"/><div className="chapter-dial" aria-hidden="true"><svg viewBox="0 0 160 160"><circle className="dial-track" cx="80" cy="80" r="68"/><motion.circle className="dial-progress" cx="80" cy="80" r="68" pathLength="100" style={{strokeDashoffset:dash}}/><motion.g className="dial-needle" style={{rotate,transformOrigin:'80px 80px'}}><path d="M80 12V28"/></motion.g></svg><div><span className="dial-count">0{active+1}</span><small>OF 03</small></div></div><motion.div className="scene-seam" aria-hidden="true" style={enabled?{x:seamX,opacity:seamOpacity,rotate:-12}:undefined}/><div className="cinema-top"><span>THE ART OF THE UPGRADE</span><span>CARTUNEZ / HYDERABAD</span></div><div className="scene-copy">{chapters.map((_,i)=><Scene key={i} index={i} progress={progress} active={active}/>)}</div><div className="cinema-bottom"><div className="scene-tabs" aria-label="Experience chapters">{chapters.map((_,i)=><ChapterButton key={i} index={i} progress={progress} active={active} onClick={()=>go(i)}/>)}</div><span className="scene-counter" aria-hidden="true">0{active+1} / 03</span></div></div></section>
}
